/**
 * Centralized icon exports from lucide-react
 *
 * This file provides a single source of truth for all icons used in the application.
 * Benefits:
 * - Improved tree-shaking efficiency
 * - Easier icon management and refactoring
 * - Clear visibility of which icons are actually used
 * - Better code organization
 *
 * Usage:
 * import { Calculator, ArrowLeft } from '@/icons';
 */

// Export all icons used across the application in alphabetical order
export {
  Activity,
  AlignCenter,
  AlignLeft,
  AlignRight,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Calendar,
  Calculator,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudOff,
  CloudUpload,
  Copy,
  Database,
  Dot,
  Download,
  Eye,
  FileJson,
  FileText,
  Gavel,
  Grid3x3,
  GripVertical,
  HelpCircle,
  Info,
  Keyboard,
  Layers,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  MessageSquare,
  Minimize2,
  MoreHorizontal,
  Move,
  MoveHorizontal,
  MoveVertical,
  Package,
  PanelLeft,
  PanelLeftClose,
  PanelRightClose,
  Phone,
  Play,
  Plus,
  RefreshCw,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  Sparkles,
  Trash2,
  Upload,
  User,
  Users,
  X,
  XCircle,
} from 'lucide-react';
